#include <iostream>
using namespace std;
int main() {
	setlocale(0, "");

int a = 122;
cout << "a = " << a << "Тип int, размер 4" << endl;
int b = 123;
cout << "b = " << b << "Тип int, размер 4" << endl;
int c = 123;
cout << "c = " << c << "Тип int, размер 4" << endl;
int d = 123;
cout << "d = " << d << "Тип int, размер 4" << endl;
int e = 123;
cout << "e = " << e << "Тип int, размер 4" << endl;
int f = 123;
cout << "f = " << f << "Тип int, размер 4" << endl;
int g = 123;
cout << "g = " << g << "Тип int, размер 4" << endl;
int h = 123;
cout << "h = " << h << "Тип int, размер 4" << endl;
int i = 123;
cout << "i = " << i << "Тип int, размер 4" << endl;
int j = 123;
cout << "j = " << j << "Тип int, размер 4" << endl;

char gd = '1';
cout << "gd = " << gd << "Тип char, размер 1" << endl;
char gm = '2';
cout << "gm = " << gm << "Тип char, размер 1 " << endl;
char ga = '4';
cout << "ga = " << ga << "Тип char, размер 1" << endl;
char gs = '5';
cout << "gs = " << gs << "Тип char, размер 1" << endl;
char gx = '6';
cout << "gx = " << gx << "Тип char, размер 1" << endl;
char gl = '7';
cout << "gl = " << gl << "Тип char, размер 1" << endl;
char go = '8';
cout << "go = " << go << "Тип char, размер 1" << endl;
char gy = '9';
cout << "gy = " << gy << "Тип char, размер 1" << endl;
char gp = '310';
cout << "gp = " << gp << "Тип char, размер 1" << endl;

float gly = 2,41;
cout << "gly = " << gly << "тип float, размер 4" << endl;
float gym = 2,4;
cout << "gym = " << gym << "тип float, размер 4" << endl;
float gys = 2,57;
cout << "gyw = " << gys << "тип float, размер 4" << endl;
float gyx = 2,6;
cout << "gyx = " << gyx << "тип float, размер 4" << endl;
float gyc = 2,7;
cout << "gyc = " << gyc << "тип float, размер 4" << endl;
float gyv = 2,95;
cout << "gyv = " << gyv << "тип float, размер 4" << endl;
float gyb = 2,14;
cout << "gyb = " << gyb << "тип float, размер 4" << endl;
float gyn = 2,38;
cout << "gyn = " << gyn << "тип float, размер 4" << endl;
float gyl = 2,33;
cout << "gyl = " << gyl << "тип float, размер 4" << endl;
float gyo = 2, 8;
cout << "gyo = " << gyo << "тип float, размер 4" << endl;

double cash = 8;
cout << "cash = " << cash << "Тип double, размер 8" << endl;
double master = 18;
cout << "master = " << master << "Тип double, размер 8" << endl;
double masterw = 18;
cout << "masterw = " << masterw << "Тип double, размер 8" << endl;
double masterr = 18;
cout << "masterr = " << masterr << "Тип double, размер 8" << endl;
double masterd = 18;
cout << "masterd = " << masterd << "Тип double, размер 8" << endl;
double masterx = 18;
cout << "masterx = " << masterx << "Тип double, размер 8" << endl;
double masterxxx = 18;
cout << "masterxxx = " << masterxxx << "Тип double, размер 8" << endl;
double masterxx = 18;
cout << "masterxx = " << masterxx << "Тип double, размер 8" << endl;
double masterday = 18;
cout << "masterday = " << masterday << "Тип double, размер 8" << endl;
double masteroil = 18;
cout << "masteroil = " << masteroil << "Тип double, размер 8" << endl;

short xac = 12;
cout << "xac = " << xac << " Тип short, размер 2" << endl;
short xba = 23;
cout << "xba = " << xba << " Тип short, размер 2" << endl;
short xcd = 33;
cout << "xcd = " << xcd << " Тип short, размер 2" << endl;
short xdx = 44;
cout << "xdx = " << xdx << " Тип short, размер 2" << endl;
short xed = 55;
cout << "xed = " << xed << " Тип short, размер 2" << endl;
short xfi = 66;
cout << "xfi = " << xfi << " Тип short, размер 2" << endl;
short xgx = 79;
cout << "xgx = " << xgx << " Тип short, размер 2" << endl;
short xhh = 88;
cout << "xhh = " << xhh << " Тип short, размер 2" << endl;
short xiu = 99;
cout << "xiu = " << xiu << " Тип short, размер 2" << endl;
short xji = 109;
cout << "xji = " << xji << " Тип short, размер 2" << endl << endl;

long dungeon = 15325;
cout << "dungeon = " << dungeon << " Тип long, размер 4" << endl;
long zb = 2436464;
cout << "zb = " << zb << " Тип long, размер 4" << endl;
long zc = 3333;
cout << "zc = " << zc << " Тип long, размер 4" << endl;
long zd = 4444;
cout << "zd = " << zd << " Тип long, размер 4" << endl;
long ze = 555;
cout << "ze = " << ze << " Тип long, размер 4" << endl;
long zf =182;
cout << "zf = " << zf << " Тип long, размер 4" << endl;
long zg = 153;
cout << "zg = " << zg << " Тип long, размер 4" << endl;
long zh = 1412414;
cout << "zh = " << zh << " Тип long, размер 4" << endl;
long zi = 94557;
cout << "zi = " << zi << " Тип long, размер 4" << endl;
long zj = 103535353;
cout << "zj = " << zj << " Тип long, размер 4" << endl;

bool ikea = true;
cout << "ikea = " << ikea << "Тип bool, размер 1" << endl;
bool ikez = false;
cout << "ikez = " << ikez << "Тип bool, размер 1" << endl;


